#!/usr/bin/env python3
"""Regenerate the documentation pages that are derived from configuration.

    python3 tools/render_docs.py           # write the files
    python3 tools/render_docs.py --check   # fail if they are out of date

Two pages are generated rather than written by hand, so that the documentation
cannot drift away from the configuration that actually drives decisions:

    docs/03-questionnaire.md
    docs/04-mapping-and-portfolios.md
    docs/08-control-index.md

``tests/test_docs.py`` runs the --check mode.
"""

from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from suitability.config import load_config  # noqa: E402

BANNER = "<!-- generated by tools/render_docs.py - do not edit by hand -->"


def render_questionnaire(cfg) -> str:
    out: list[str] = [
        "# 3. The questionnaire",
        "",
        BANNER,
        "",
        f"Questionnaire version **{cfg.questionnaire['meta']['version']}**, effective "
        f"{cfg.questionnaire['meta']['effective_from']}. "
        f"Review cycle: **{cfg.questionnaire['meta']['review_cycle_months']} months** "
        "(Art. 54(13) DR 2017/565, ESMA GL5).",
        "",
        "Scores in brackets are the option's contribution to its dimension before "
        "weighting. A `*` marks the correct answer to an objective comprehension item. "
        "Questions marked *cross-check only* carry no weight and exist to detect "
        "over-estimation (ESMA GL4 paras 46, 52).",
        "",
        "## Design rules",
        "",
        "1. No question asks the client to certify their own suitability or to pick "
        "their own risk level (GL1 para 14).",
        "2. Self-declared knowledge is never scored (GL4 para 46).",
        "3. Loss questions are shown with the equivalent monetary amount (GL4 para 48).",
        "4. Sustainability preferences are collected separately and applied only after "
        "the Art. 25(2) assessment (GL8 para 81).",
        "5. No answer that widens the product range is made easier to give than one "
        "that narrows it (Art. 55(2)).",
        "",
    ]

    for section in cfg.questionnaire["sections"]:
        dim = section.get("dimension")
        out.append(f"## Section {section['id']} - {section['name']}")
        out.append("")
        if section.get("scored"):
            out.append(f"Scored. Feeds the **{dim}** dimension.")
        else:
            out.append("Not scored.")
        if section.get("applied_after_suitability"):
            out.append("Applied only after the Art. 25(2) assessment is complete.")
        out.append("")
        for basis in section.get("regulatory_basis", []) or []:
            out.append(f"> {basis}")
        out.append("")

        for q in section.get("questions", []):
            flag = ""
            if q.get("scoring_role") == "cross_check_only":
                flag = " *(cross-check only, not scored)*"
            elif q.get("scoring_role") == "comprehension":
                flag = " *(objective comprehension item)*"
            required = "required" if q.get("required") else "conditional"
            out.append(f"**{q['id']}.** {q['text']}{flag}")
            out.append("")
            out.append(f"`type: {q['type']}` · `{required}`")
            if q.get("depends_on"):
                dep = ", ".join(f"{k} in {v}" for k, v in q["depends_on"].items())
                out.append(f" · shown when {dep}")
            out.append("")
            if q.get("help"):
                out.append(f"> {q['help'].strip()}")
                out.append("")
            for opt in q.get("options", []) or []:
                mark = "*" if opt.get("correct") else "-"
                bits = []
                if opt.get("score") is not None:
                    bits.append(f"score {opt['score']}")
                for key in ("tier", "objective_band", "horizon_band", "horizon_years",
                            "capacity_loss_pct", "tolerance_loss_pct", "implied_band",
                            "min_proportion", "portfolio_share", "self_rating"):
                    if key in opt:
                        bits.append(f"{key} {opt[key]}")
                suffix = f"  <sub>{', '.join(bits)}</sub>" if bits else ""
                out.append(f"{mark} {opt['label']}{suffix}")
            out.append("")

    return "\n".join(out).rstrip() + "\n"


def render_mapping(cfg) -> str:
    out: list[str] = [
        "# 4. Mapping and the model portfolio range",
        "",
        BANNER,
        "",
        f"Portfolio configuration version **{cfg.portfolios['meta']['version']}**. "
        f"Costs are {cfg.portfolios['meta']['cost_basis']}.",
        "",
        "## 4.1 Risk bands",
        "",
        "| Band | Label | Adverse 12-month loss | Loss on EUR 100,000 |",
        "|---|---|---|---|",
    ]
    for band in range(0, 6):
        rb = cfg.portfolios["risk_bands"].get(band, {})
        if band == 0:
            out.append(f"| 0 | {rb.get('label','-')} | n/a | n/a |")
            continue
        loss = rb.get("stress_loss_pct", 0)
        out.append(f"| {band} | {rb.get('label','-')} | {loss}% | EUR {100000*loss/100:,.0f} |")

    out += [
        "",
        "Band 0 is a real outcome, not an error state: a client who cannot absorb any "
        "permanent loss of the amount concerned has no suitable model portfolio in this "
        "range, and the framework says so rather than defaulting to the lowest band.",
        "",
        "## 4.2 Complexity tiers",
        "",
        "| Tier | Instruments |",
        "|---|---|",
    ]
    for tier, desc in sorted(cfg.portfolios["complexity_tiers"].items()):
        out.append(f"| {tier} | {desc} |")

    out += [
        "",
        "## 4.3 The knowledge gate",
        "",
        "| Knowledge band | Maximum complexity tier |",
        "|---|---|",
    ]
    for band, tier in sorted(cfg.scoring["complexity_gate"].items()):
        out.append(f"| {band} | {tier} |")

    out += [
        "",
        "Art. 54(3) DR 2017/565: for professional clients the firm may assume the "
        "necessary knowledge and experience, and the gate opens fully.",
        "",
        "## 4.4 The model portfolio range",
        "",
        "| id | band | SRI | adverse loss | min horizon | tier | cost (bps) | Taxonomy min | SFDR min | PAI |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for p in cfg.all_portfolios():
        s = p.get("sustainability", {}) or {}
        out.append(
            f"| `{p['id']}` | {p['risk_band']} | {p['sri']}/7 | {p['stress_loss_pct']}% | "
            f"{p['min_horizon_years']}y | {p['complexity_tier']} | {p['total_cost_bps']} | "
            f"{s.get('taxonomy_min', 0):.0%} | {s.get('sfdr_sustainable_min', 0):.0%} | "
            f"{'yes' if s.get('pai_considered') else 'no'} |"
        )

    out += [
        "",
        "Each band carries a Core variant with no sustainability claim, a PAI-aware "
        "variant addressing Art. 2(7)(c), and a Sustainable variant with minimum "
        "proportions under Art. 2(7)(a) and (b). ESMA GL2 para 29: model portfolios must "
        "not force clients into a predetermined combination of sustainability "
        "preferences.",
        "",
        "## 4.5 Asset allocation",
        "",
        "| id | " + " | ".join(_allocation_keys(cfg)) + " |",
        "|---|" + "---|" * len(_allocation_keys(cfg)),
    ]
    for p in cfg.all_portfolios():
        alloc = p.get("allocation", {}) or {}
        row = " | ".join(f"{alloc.get(k, 0)}%" for k in _allocation_keys(cfg))
        out.append(f"| `{p['id']}` | {row} |")

    cc = cfg.portfolios["construction_constraints"]
    out += [
        "",
        "## 4.6 Construction constraints",
        "",
        "Applied to every model. ESMA GL8 para 89.",
        "",
        f"- Maximum single issuer: **{cc['max_single_issuer_pct']}%** "
        f"({cc['max_single_issuer_pct_sovereign_ig']}% for investment-grade sovereigns)",
        f"- Maximum exposure to instruments issued by the firm's own group: "
        f"**{cc['max_own_group_instruments_pct']}%**",
        f"- Minimum number of underlying holdings: **{cc['min_number_of_underlying_holdings']}**",
        "- Maximum illiquid exposure by band: "
        + ", ".join(f"band {b} {v}%" for b, v in sorted(cc["max_illiquid_pct_by_band"].items())),
        f"- Below **EUR {cc['small_portfolio_threshold_eur']:,}**: {cc['small_portfolio_rule'].strip()}",
        "",
        "## 4.7 Choosing among equivalents",
        "",
        f"{cfg.portfolios['equivalence_rule']['definition'].strip()}",
        "",
        f"Selection rule: `{cfg.portfolios['equivalence_rule']['selection']}`. "
        f"A justification is required when {cfg.portfolios['equivalence_rule']['justification_required_when']}, "
        "on the grounds of "
        + ", ".join(cfg.portfolios["equivalence_rule"]["justification_grounds"])
        + f". Recorded: {cfg.portfolios['equivalence_rule']['record']}. "
        "(Art. 54(9) DR 2017/565; ESMA GL9 paras 91-95.)",
        "",
        "## 4.8 Switching",
        "",
        f"{cfg.portfolios['switching']['test'].strip()}",
        "",
        f"- Breakeven must fall inside **{cfg.portfolios['switching']['breakeven_horizon_cap_years']} years** "
        "and inside the client's remaining horizon.",
        f"- {cfg.portfolios['switching']['rebalancing_exclusion'].strip()}",
        f"- {cfg.portfolios['switching']['anti_circumvention'].strip()}",
        "",
        "Implemented in `src/suitability/switching.py`. Art. 54(11) DR 2017/565; ESMA GL10.",
    ]
    return "\n".join(out).rstrip() + "\n"


def _allocation_keys(cfg) -> list[str]:
    keys: list[str] = []
    for p in cfg.all_portfolios():
        for k in (p.get("allocation") or {}):
            if k not in keys:
                keys.append(k)
    return keys



def render_controls(cfg) -> str:
    out: list[str] = [
        "# 8. Control index",
        "",
        BANNER,
        "",
        "ESMA GL4 para 51 is the obligation: firms should view the information collected "
        "as a whole, be alert to relevant contradictions, and contact the client to "
        "resolve material inconsistencies. GL4 para 49 describes the mechanism: "
        "risk-profiling software \"could include some controls of coherence of the replies "
        "provided by clients in order to highlight contradictions between different pieces "
        "of information collected\". These are those controls.",
        "",
        "Severity:",
        "",
        "| | |",
        "|---|---|",
        "| `block` | No recommendation may be produced until the issue is resolved |",
        "| `refer` | The recommendation is withheld pending an adviser conversation with the client, which is documented |",
        "| `cap`   | The profile is capped automatically and the client is told |",
        "| `note`  | Recorded on file, no automatic effect |",
        "",
        "Every control is one-way: it can hold a profile where it is or move it down. "
        "None can move it up.",
        "",
        "| id | severity | control | condition | effect | basis |",
        "|---|---|---|---|---|---|",
    ]
    for c in cfg.scoring["coherence_controls"]:
        cond = str(c.get("condition", "")).replace("|", "\\|")
        effect = " ".join(str(c.get("effect", "")).split())
        basis = " ".join(str(c.get("basis", "")).split())
        out.append(
            f"| `{c['id']}` | `{c['severity']}` | {c['name']} | `{cond}` | {effect} | {basis} |"
        )

    out += [
        "",
        "## Client-facing wording",
        "",
        "What the suitability report says to the client when each control fires.",
        "",
    ]
    for c in cfg.scoring["coherence_controls"]:
        msg = " ".join(str(c.get("client_message", "")).split())
        out.append(f"**{c['id']} — {c['name']}**")
        out.append("")
        out.append(f"> {msg}")
        out.append("")

    out += [
        "## Where the conditions live",
        "",
        "The severity, regulatory basis, stated effect and client wording of every control "
        "are configuration, in `config/scoring.yaml`. The **conditions** are implemented in "
        "code, in `src/suitability/consistency.py`, and not evaluated from strings: a "
        "suitability control that can be switched off by editing a text expression is not a "
        "control. `tests/test_consistency.py::test_every_configured_control_is_implemented` "
        "keeps the two lists in step, and there is one test per control.",
    ]
    return "\n".join(out).rstrip() + "\n"


TARGETS = {
    "docs/03-questionnaire.md": render_questionnaire,
    "docs/04-mapping-and-portfolios.md": render_mapping,
    "docs/08-control-index.md": render_controls,
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    cfg = load_config(os.path.join(ROOT, "config"))
    stale: list[str] = []
    for relpath, renderer in TARGETS.items():
        path = os.path.join(ROOT, relpath)
        content = renderer(cfg)
        if args.check:
            existing = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
            if existing != content:
                stale.append(relpath)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            print(f"wrote {relpath}")

    if stale:
        print("out of date: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
